version: '3'

services:
  
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    expose:
      - "3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    build: 
      context: nginx
    image: jhenriquefsantana/nginx:latest
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge